default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hackathon_3d_dev

test:
  <<: *default
  database: hackathon_3d_test
